Install maven

diff --git a/mta-archive-builder/Dockerfile b/mta-archive-builder/Dockerfile
--- a/mta-archive-builder/Dockerfile
+++ b/mta-archive-builder/Dockerfile
@@ -1,4 +1,4 @@
-FROM openjdk:8-jre-slim
+FROM openjdk:8-jdk-slim
 
 ARG MTA_USER_HOME=/home/mta
 ARG MTA_HOME='/opt/sap/mta'
@@ -6,7 +6,11 @@ ARG MTA_VERSION=1.1.7
 
 ARG NODE_VERSION=v10.13.0
 
+ARG MAVEN_VERSION=3.6.0
+
 ENV MTA_JAR_LOCATION="${MTA_HOME}/lib/mta.jar"
+
+ENV M2_HOME=/opt/maven/apache-maven-${MAVEN_VERSION}
 
 ADD scripts/mtaBuild.sh ${MTA_HOME}/bin/mtaBuild.sh
 
@@ -44,6 +48,17 @@ RUN apt-get update && apt-get install -y \
     #
     npm config set @sap:registry https://npm.sap.com --global && \
     #
+    # Install maven
+    #
+    echo "[INFO] installing maven." && \
+    M2_BASE=`dirname ${M2_HOME}` && \
+    mkdir -p ${M2_BASE} && \
+    curl --fail --silent --output - https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
+      | tar -xzvf - -C ${M2_BASE} && \
+    ln -s ${M2_HOME}/bin/mvn /usr/local/bin/mvn && \
+    INSTALLED_MAVEN_VERSION=`mvn -version |head -n1 |cut -d ' ' -f  3` && \
+    echo "[INFO] maven version: \"${INSTALLED_MAVEN_VERSION}\"." && \
+    #
     # Cleanup curl (was only needed for downloading artifacts)
     #
     apt-get remove --purge --autoremove -y \
@@ -62,7 +77,8 @@ RUN apt-get update && apt-get install -y \
     # when demanding version 1.1.7. When activating the check below, don't forget to add
     # ' && \' to the line above
     # [ "${MTA_VERSION}" = "${INSTALLED_MTA_VERSION}" ] || { echo "[ERROR] Installed mta version '${INSTALLED_MTA_VERSION}' does not match expected mta version '${MTA_VERSION}'."; exit 1; }
-   [ "${NODE_VERSION}" = "${INSTALLED_NODE_VERSION}" ] || { echo "[ERROR] Installed node version '${INSTALLED_NODE_VERSION}' does not match expected node version '${NODE_VERSION}'."; exit 1; }
+   [ "${NODE_VERSION}" = "${INSTALLED_NODE_VERSION}" ] || { echo "[ERROR] Installed node version '${INSTALLED_NODE_VERSION}' does not match expected node version '${NODE_VERSION}'."; exit 1; } && \
+   [ "${MAVEN_VERSION}" = "${INSTALLED_MAVEN_VERSION}" ] || { echo "[ERROR] Installed maven version '${INSTALLED_MAVEN_VERSION}' does not match expected maven version '${MAVEN_VERSION}'."; exit 1; }
 
 WORKDIR /project
 
